// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwnqsrmudpciexmnezbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bnFzcm11ZHBjaWV4bW5lemJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzIyNzksImV4cCI6MjA1NzcwODI3OX0.6jzTpRiIHV3dphphmhh8R8OBDk67pKeQlJlddzxP8kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);